[package]
name = "modern-multiset"
version = "0.0.0"
authors = ["Sebastian Schmidt <isibboi@gmail.com>"]
repository = "https://github.com/ISibboI/multiset"
description = "A hash multiset implementation."
keywords = ["multiset", "data-structure", "collection", "count", "hash"]
license = "GPLv3"
